# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(default='live', max_length=300),
            preserve_default=False,
        ),
    ]
