# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170909_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='code',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='code',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
