# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170910_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='flag',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
