# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_team_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='nationality',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='flag',
            field=models.CharField(max_length=500),
        ),
    ]
