# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170910_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='headshot',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
