# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_player_headshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='team_a_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='team_b_score',
            field=models.IntegerField(default=0),
        ),
    ]
