# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20170910_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_period',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
