# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_game_current_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_period',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_a_score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_b_score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
