# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20170910_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='start_time',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
