# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20170910_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_code', models.CharField(max_length=30)),
                ('action_text', models.CharField(blank=True, max_length=100, null=True)),
                ('action_uid', models.IntegerField(blank=True, default=0, null=True)),
                ('time', models.CharField(blank=True, max_length=30, null=True)),
                ('epoch_time', models.BigIntegerField(blank=True, null=True)),
                ('shot_x', models.IntegerField(blank=True, null=True)),
                ('shot_y', models.IntegerField(blank=True, null=True)),
                ('score', models.CharField(blank=True, max_length=30, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Game')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions_player', to='main.Player')),
                ('subs_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions_subs_in', to='main.Player')),
            ],
        ),
    ]
