# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_game_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=300)),
                ('code', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='time',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='game',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
