# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20170912_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Location'),
        ),
    ]
