# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20170912_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='team_a_foul',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='team_b_foul',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
