# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20170912_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='team_a_period_scores',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='game',
            name='team_b_period_scores',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
