# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20170912_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='plus_minus',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
