# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_actions_plus_minus'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Team'),
        ),
    ]
