# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_actions_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='team_a_score',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='actions',
            name='team_b_score',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
