# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20170912_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actions',
            name='team_a_score',
        ),
        migrations.RemoveField(
            model_name='actions',
            name='team_b_score',
        ),
    ]
