# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20170912_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='team_a_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actions',
            name='team_b_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
