# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20170913_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='team_a_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_b_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
