# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20170916_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(blank=True, default='future', max_length=300),
        ),
    ]
