# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20170916_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actions',
            options={'ordering': ['-action_uid']},
        ),
    ]
