# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_game_init_scrape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='init_scrape',
            field=models.BooleanField(default=True),
        ),
    ]
