# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20170919_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='period',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
