# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_actions_period'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actions',
            options={'ordering': ['-period', '-action_uid']},
        ),
        migrations.AddField(
            model_name='player',
            name='shirt_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
